In [1]:
import pandas as pd

flights = pd.read_csv("../data/raw/flights.csv")

print(flights.shape)
flights.head()

/var/folders/nt/7_1wj32n13x9p7f_84zzxjsh0000gn/T/ipykernel_9119/788100320.py:3: DtypeWarning: Columns (7: ORIGIN_AIRPORT, 8: DESTINATION_AIRPORT) have mixed types. Specify dtype option on import or set low_memory=False.
  flights = pd.read_csv("../data/raw/flights.csv")

(5819079, 31)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
print(flights.shape)
flights.head()

(5819079, 31)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print(flights.columns.tolist())
print()
print(flights.isnull().sum())

['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'FLIGHT_NUMBER', 'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT', 'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'TAXI_OUT', 'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME', 'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON', 'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY', 'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY']

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           86153
DEPARTURE_DELAY          86153
TAXI_OUT                 89047
WHEELS_OFF               89047
SCHEDULED_TIME               6
ELAPSED_TIME            105071
AIR_TIME                105071
DISTANCE                     0
WHEELS_ON                92513
TAXI_IN                  92513
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             92513
ARRIVAL_DELAY           105071
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4755640
SECURITY_DELAY         4755640
AIRLINE_DELAY          4755640
LATE_AIRCRAFT_DELAY    4755640
WEATHER_DELAY          4755640
dtype: int64

In [4]:
print(flights.shape)

(5819079, 31)

In [5]:
flights_clean = flights[[
    'YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK',
    'AIRLINE', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
    'SCHEDULED_DEPARTURE', 'SCHEDULED_ARRIVAL',
    'DISTANCE', 'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED'
]].copy()

print(flights_clean.shape)

(5819079, 13)

In [6]:
flights_clean = flights_clean[
    (flights_clean['CANCELLED'] == 0) & (flights_clean['DIVERTED'] == 0)
].copy()

print(flights_clean.shape)
print(flights_clean['ARRIVAL_DELAY'].isnull().sum())

(5714008, 13)
0

In [7]:
print(flights_clean.isnull().sum())

YEAR                   0
MONTH                  0
DAY                    0
DAY_OF_WEEK            0
AIRLINE                0
ORIGIN_AIRPORT         0
DESTINATION_AIRPORT    0
SCHEDULED_DEPARTURE    0
SCHEDULED_ARRIVAL      0
DISTANCE               0
ARRIVAL_DELAY          0
DIVERTED               0
CANCELLED              0
dtype: int64

In [8]:
flights_clean['IS_DELAYED'] = (flights_clean['ARRIVAL_DELAY'] >= 15).astype(int)
print(flights_clean['IS_DELAYED'].value_counts())
print(flights_clean['IS_DELAYED'].value_counts(normalize=True))

IS_DELAYED
0    4650569
1    1063439
Name: count, dtype: int64
IS_DELAYED
0    0.813889
1    0.186111
Name: proportion, dtype: float64

In [9]:
flights_clean['ORIGIN_AIRPORT'].apply(type).value_counts()

ORIGIN_AIRPORT
<class 'str'>    5258011
<class 'int'>     455997
Name: count, dtype: int64

In [10]:
flights_clean['FLIGHT_DATE'] = pd.to_datetime(
    flights_clean[['YEAR', 'MONTH', 'DAY']]
)
print(flights_clean['FLIGHT_DATE'].min(), "to", flights_clean['FLIGHT_DATE'].max())

2015-01-01 00:00:00 to 2015-12-31 00:00:00

In [11]:
print(flights_clean.duplicated().sum())

3

In [12]:
flights_clean['ORIGIN_AIRPORT'] = flights_clean['ORIGIN_AIRPORT'].astype(str)
flights_clean['DESTINATION_AIRPORT'] = flights_clean['DESTINATION_AIRPORT'].astype(str)

flights_clean = flights_clean.drop_duplicates()
print(flights_clean.shape)

(5714005, 15)

In [17]:
flights_clean.to_csv("../data/processed/flights_cleaned.csv", index=False)
print("Saved:", flights_clean.shape)

Saved: (5714005, 15)